= Building a gRPC Web service
:page-permalink: /
:page-github: vertx-howtos/grpc-web-howto

ifdef::env-github[]
image:https://github.com/vertx-howtos/grpc-web-howto/workflows/Publish%20the%20how-to/badge.svg["Build Status",link="https://github.com/vertx-howtos/grpc-web-howto/actions?query=workflow%3A%22Publish+the+how-to%22"]
endif::env-github[]

This document will show you how to build a https://github.com/grpc/grpc-web[gRPC Web] service with Vert.x.

== What you will build

You will build a gRPC _Greeter_ client/server application, using the gRPC Web protocol.

On the server side, you will implement a Vert.x gRPC server service that:

* implements a gRPC server stub
* configures an HTTP server replying to both gRPC Web and static file requests

On the client side, you will create a browser page that uses the gRPC Web Javascript client.

== What you need

* A text editor or an IDE
* Java 17 or higher

== Create the project

=== gRPC service definition

The gRPC `Greeter` service consists in a single `SayHello` rpc method.
The `HelloRequest` message contains the name sent by the client.
The `HelloReply` message contains the greeting generated by the server.

ifdef::env-github[]
link:src/main/proto/service.proto[`service.proto` file]
endif::env-github[]
ifndef::env-github[]
[source,xml]
.`service.proto` file
----
include::src/main/proto/service.proto[]
----
endif::env-github[]
